return {}
-- {
--   'kiddos/gemini.nvim',
--   config = function()
--     require('gemini').setup {
--       completion = {
--         enabled = false,
--       },
--     }
--   end,
-- },
-- return {
--   'Exafunction/codeium.vim',
--   cmd = 'CodeiumToggle',
--   lazy = true,
--   init = function()
--     vim.g.codeium_disable_bindings = 1
--     vim.g.codeium_enabled = false
--   end,
--   config = function()
--     vim.api.nvim_create_user_command('CodeiumChat', function()
--       vim.fn['codeium#Chat']()
--     end, {})
--     local key = vim.keymap.set
--     local opts = { expr = true, silent = true }
--     key('i', '<C-g>', function()
--       return vim.fn['codeium#Accept']()
--     end, opts)
--     key('i', '<c-p>', function()
--       return vim.fn['codeium#CycleCompletions'](1)
--     end, opts)
--     key('i', '<c-n>', function()
--       return vim.fn['codeium#CycleCompletions'](-1)
--     end, opts)
--     key('i', '<c-x>', function()
--       return vim.fn['codeium#Clear']()
--     end, opts)
--   end,
-- }
-- return {
--   'Exafunction/codeium.nvim',
--   dependencies = {
--     'nvim-lua/plenary.nvim',
--     'hrsh7th/nvim-cmp',
--   },
--   config = function()
--     require('codeium').setup {
--       bin_path='/data/data/com.termux/files/home/.codeium/bin',
--       virtual_text = {
--         enabled = true,
--         map_keys = false,
--         key_bindings = {
--           -- Accept the current completion.
--           accept = '<C-g>',
--           -- Accept the next word.
--           accept_word = false,
--           -- Accept the next line.
--           accept_line = false,
--           -- Clear the virtual text.
--           clear = false,
--           -- Cycle to the next completion.
--           next = '<C-n>',
--           -- Cycle to the previous completion.
--           prev = '<C-p>',
--         },
--       },
--     }
--   end,
-- }
