vim.lsp.enable('html')
-- lsp.html = {
--   filetypes = { 'html', 'javascript', 'typescript' },
--   init_options = {
--     configurationSection = { 'html', 'javascript', 'typescript', 'css' },
--     embeddedLanguages = {
--       css = true,
--       javascript = true,
--       typescript = true,
--     },
--   },
-- }